const data = [
	{
		month: [
			{ date: 26, disable: 'disable', rest: 'rest' },
			{ date: 27, disable: 'disable' },
			{ date: 28, disable: 'disable' },
			{ date: 29, disable: 'disable' },
			{ date: 30, disable: 'disable' },
			{ date: 31, disable: 'disable' },
			{
				date: 1,
				disable: 'disable',
				rest: 'rest',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ Tết dương lịch',
			},
			{ date: 2, rest: 'rest' },
			{
				date: 3,
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ bù tết dương lịch 1/1/2022',
			},
			{ date: 4 },
			{ date: 5 },
			{ date: 6 },
			{ date: 7 },
			{ date: 8, rest: 'rest' },
			{ date: 9, rest: 'rest' },
			{ date: 10 },
			{ date: 11 },
			{ date: 12 },
			{ date: 13 },
			{ date: 14 },
			{ date: 15, rest: 'rest' },
			{ date: 16, rest: 'rest' },
			{ date: 17 },
			{ date: 18 },
			{ date: 19 },
			{ date: 20 },
			{ date: 21 },
			{ date: 22, rest: 'rest' },
			{ date: 23, rest: 'rest' },
			{ date: 24 },
			{ date: 25 },
			{ date: 26 },
			{ date: 27 },
			{ date: 28 },
			{
				date: 29,
				disable: 'disable',
				rest: 'rest',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{
				date: 30,
				disable: 'disable',
				rest: 'rest',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{
				date: 31,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
			{ date: 3, disable: 'disable' },
			{ date: 4, disable: 'disable' },
			{ date: 5, disable: 'disable', rest: 'rest' },
		],
	},
	{
		month: [
			{ date: 30, disable: 'disable', rest: 'rest' },
			{ date: 31, disable: 'disable' },
			{
				date: 1,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{
				date: 2,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{
				date: 3,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{
				date: 4,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{
				date: 5,
				disable: 'disable',
				rest: 'rest',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{
				date: 6,
				disable: 'disable',
				rest: 'rest',
				title: 'Nghỉ tết Nguyên Đán - Nhâm Dần 2022',
			},
			{ date: 7 },
			{ date: 8 },
			{ date: 9 },
			{ date: 10 },
			{ date: 11 },
			{ date: 12, rest: 'rest' },
			{ date: 13, rest: 'rest' },
			{ date: 14 },
			{ date: 15 },
			{ date: 16 },
			{ date: 17 },
			{ date: 18 },
			{ date: 19, rest: 'rest' },
			{ date: 20, rest: 'rest' },
			{ date: 21 },
			{ date: 22 },
			{ date: 23 },
			{ date: 24 },
			{ date: 25 },
			{ date: 26, rest: 'rest' },
			{ date: 27, rest: 'rest' },
			{ date: 28 },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
			{ date: 3, disable: 'disable' },
			{ date: 4, disable: 'disable' },
			{ date: 5, disable: 'disable' },
		],
	},
	{
		month: [
			{ date: 27, disable: 'disable', rest: 'rest' },
			{ date: 28, disable: 'disable' },
			{ date: 1 },
			{ date: 2 },
			{ date: 3 },
			{ date: 4 },
			{ date: 5, rest: 'rest' },
			{ date: 6, rest: 'rest' },
			{ date: 7 },
			{ date: 8 },
			{ date: 9 },
			{ date: 10 },
			{ date: 11 },
			{ date: 12, rest: 'rest' },
			{ date: 13, rest: 'rest' },
			{ date: 14 },
			{ date: 15 },
			{ date: 16 },
			{ date: 17 },
			{ date: 18 },
			{ date: 19, rest: 'rest' },
			{ date: 20, rest: 'rest' },
			{ date: 21 },
			{ date: 22 },
			{ date: 23 },
			{ date: 24 },
			{ date: 25 },
			{ date: 26, rest: 'rest' },
			{ date: 27, rest: 'rest' },
			{ date: 28 },
			{ date: 29 },
			{ date: 30 },
			{ date: 31 },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
		],
	},
	{
		month: [
			{ date: 27, disable: 'disable', rest: 'rest' },
			{ date: 28, disable: 'disable' },
			{ date: 29, disable: 'disable' },
			{ date: 30, disable: 'disable' },
			{ date: 31, disable: 'disable' },
			{ date: 1 },
			{ date: 2, rest: 'rest' },
			{ date: 3, rest: 'rest' },
			{ date: 4 },
			{ date: 5 },
			{ date: 6 },
			{ date: 7 },
			{ date: 8 },
			{
				date: 9,
				icon: 'bx bx-calendar-alt',
				title: 'Giỗ Tổ Hùng Vương',
				disable: 'disable',
				rest: 'rest',
			},
			{
				date: 10,
				icon: 'bx bx-calendar-alt',
				title: 'Giỗ Tổ Hùng Vương',
				disable: 'disable',
				rest: 'rest',
			},
			{
				date: 11,
				icon: 'bx bx-calendar-alt',
				title: 'Giỗ Tổ Hùng Vương',
				disable: 'disable',
			},
			{ date: 12 },
			{ date: 13 },
			{ date: 14 },
			{ date: 15 },
			{ date: 16, rest: 'rest' },
			{ date: 17, rest: 'rest' },
			{ date: 18 },
			{ date: 19 },
			{ date: 20 },
			{ date: 21 },
			{ date: 22 },
			{ date: 23, rest: 'rest' },
			{ date: 24, rest: 'rest' },
			{ date: 25 },
			{ date: 26 },
			{ date: 27 },
			{ date: 28 },
			{ date: 29 },
			{
				date: 30,
				disable: 'disable',
				rest: 'rest',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ 30/4 - 1/5',
			},
		],
	},
	{
		month: [
			{
				date: 1,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ 30/4- 1/5',
			},
			{
				date: 2,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ bù 30/4 - 1/5',
			},
			{
				date: 3,
				disable: 'disable',
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ bù 30/4 - 1/5',
			},
			{ date: 4 },
			{ date: 5 },
			{ date: 6 },
			{ date: 7, rest: 'rest' },
			{ date: 8, rest: 'rest' },
			{ date: 9 },
			{ date: 10 },
			{ date: 11 },
			{ date: 12 },
			{ date: 13 },
			{ date: 14, rest: 'rest' },
			{ date: 15, rest: 'rest' },
			{ date: 16 },
			{ date: 17 },
			{ date: 18 },
			{ date: 19 },
			{ date: 20 },
			{ date: 21, rest: 'rest' },
			{ date: 22, rest: 'rest' },
			{ date: 23 },
			{ date: 24 },
			{ date: 25 },
			{ date: 26 },
			{ date: 27 },
			{ date: 28, rest: 'rest' },
			{ date: 29, rest: 'rest' },
			{ date: 30 },
			{ date: 31 },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
			{ date: 3, disable: 'disable' },
			{ date: 4, disable: 'disable' },
		],
	},
	{
		month: [
			{ date: 29, disable: 'disable', rest: 'rest' },
			{ date: 30, disable: 'disable' },
			{ date: 31, disable: 'disable' },
			{ date: 1 },
			{ date: 2 },
			{ date: 3 },
			{ date: 4, rest: 'rest' },
			{ date: 5, rest: 'rest' },
			{ date: 6 },
			{ date: 7 },
			{ date: 8 },
			{ date: 9 },
			{ date: 10 },
			{ date: 11, rest: 'rest' },
			{ date: 12, rest: 'rest' },
			{ date: 13 },
			{ date: 14 },
			{ date: 15 },
			{ date: 16 },
			{ date: 17 },
			{ date: 18, rest: 'rest' },
			{ date: 19, rest: 'rest' },
			{ date: 20 },
			{ date: 21 },
			{ date: 22 },
			{ date: 23 },
			{ date: 24 },
			{ date: 25 },
			{ date: 26, rest: 'rest' },
			{ date: 27, rest: 'rest' },
			{ date: 28 },
			{ date: 29 },
			{ date: 30 },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable', rest: 'rest' },
		],
	},
	{
		month: [
			{ date: 26, disable: 'disable', rest: 'rest' },
			{ date: 27, disable: 'disable' },
			{ date: 28, disable: 'disable' },
			{ date: 29, disable: 'disable' },
			{ date: 30, disable: 'disable' },
			{ date: 1 },
			{ date: 2, rest: 'rest' },
			{ date: 3, rest: 'rest' },
			{ date: 4 },
			{ date: 5 },
			{ date: 6 },
			{ date: 7 },
			{ date: 8 },
			{ date: 9, rest: 'rest' },
			{ date: 10, rest: 'rest' },
			{ date: 11 },
			{ date: 12 },
			{ date: 13 },
			{ date: 14 },
			{ date: 15 },
			{ date: 16, rest: 'rest' },
			{ date: 17, rest: 'rest' },
			{ date: 18 },
			{ date: 19 },
			{ date: 20 },
			{ date: 21 },
			{ date: 22 },
			{ date: 23, rest: 'rest' },
			{ date: 24, rest: 'rest' },
			{ date: 25 },
			{ date: 26 },
			{ date: 27 },
			{ date: 28 },
			{ date: 29 },
			{ date: 30, rest: 'rest' },
			{ date: 31, rest: 'rest' },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
			{ date: 3, disable: 'disable' },
			{ date: 4, disable: 'disable' },
			{ date: 5, disable: 'disable' },
			{ date: 6, disable: 'disable', rest: 'rest' },
		],
	},
	{
		month: [
			{ date: 31, disable: 'disable', rest: 'rest' },
			{ date: 1 },
			{ date: 2 },
			{ date: 3 },
			{ date: 4 },
			{ date: 5 },
			{ date: 6, rest: 'rest' },
			{ date: 7, rest: 'rest' },
			{ date: 8 },
			{ date: 9 },
			{ date: 10 },
			{ date: 11 },
			{ date: 12 },
			{ date: 13, rest: 'rest' },
			{ date: 14, rest: 'rest' },
			{ date: 15 },
			{ date: 16 },
			{ date: 17 },
			{ date: 18 },
			{ date: 19 },
			{ date: 20, rest: 'rest' },
			{ date: 21, rest: 'rest' },
			{ date: 22 },
			{ date: 23 },
			{ date: 24 },
			{ date: 25 },
			{ date: 26 },
			{ date: 27, rest: 'rest' },
			{ date: 28, rest: 'rest' },
			{ date: 29 },
			{ date: 30 },
			{ date: 31 },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
			{ date: 3, disable: 'disable', rest: 'rest' },
		],
	},
	{
		month: [
			{ date: 28, disable: 'disable', rest: 'rest' },
			{ date: 29, disable: 'disable' },
			{ date: 30, disable: 'disable' },
			{ date: 31, disable: 'disable' },
			{ date: 1 },
			{ date: 2, icon: 'bx bx-calendar-alt', title: 'Nghỉ lễ Quốc Khanh' },
			{
				date: 3,
				icon: 'bx bx-calendar-alt',
				title: 'Nghỉ lễ Quốc Khanh',
				rest: 'rest',
			},
			{ date: 4, rest: 'rest' },
			{ date: 5 },
			{ date: 6 },
			{ date: 7 },
			{ date: 8 },
			{ date: 9 },
			{ date: 10, rest: 'rest' },
			{ date: 11, rest: 'rest' },
			{ date: 12 },
			{ date: 13 },
			{ date: 14 },
			{ date: 15 },
			{ date: 16 },
			{ date: 17, rest: 'rest' },
			{ date: 18, rest: 'rest' },
			{ date: 19 },
			{ date: 20 },
			{ date: 21 },
			{ date: 22 },
			{ date: 23 },
			{ date: 24, rest: 'rest' },
			{ date: 25, rest: 'rest' },
			{ date: 26 },
			{ date: 27 },
			{ date: 28 },
			{ date: 29 },
			{ date: 30 },
			{ date: 1, disable: 'disable', rest: 'rest' },
		],
	},
	{
		month: [
			{ date: 25, disable: 'disable', rest: 'rest' },
			{ date: 26, disable: 'disable' },
			{ date: 27, disable: 'disable' },
			{ date: 28, disable: 'disable' },
			{ date: 29, disable: 'disable' },
			{ date: 30, disable: 'disable' },
			{ date: 1, rest: 'rest' },
			{ date: 2, rest: 'rest' },
			{ date: 3 },
			{ date: 4 },
			{ date: 5 },
			{ date: 6 },
			{ date: 7 },
			{ date: 8, rest: 'rest' },
			{ date: 9, rest: 'rest' },
			{ date: 10 },
			{ date: 11 },
			{ date: 12 },
			{ date: 13 },
			{ date: 14 },
			{ date: 15, rest: 'rest' },
			{ date: 16, rest: 'rest' },
			{ date: 17 },
			{ date: 18 },
			{ date: 19 },
			{ date: 20 },
			{ date: 21 },
			{ date: 22, rest: 'rest' },
			{ date: 23, rest: 'rest' },
			{ date: 24 },
			{ date: 25 },
			{ date: 26 },
			{ date: 27 },
			{ date: 28 },
			{ date: 29, rest: 'rest' },
			{ date: 30, rest: 'rest' },
			{ date: 31 },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
			{ date: 3, disable: 'disable' },
			{ date: 4, disable: 'disable' },
			{ date: 5, disable: 'disable', rest: 'rest' },
		],
	},
	{
		month: [
			{ date: 30, disable: 'disable', rest: 'rest' },
			{ date: 31 },
			{ date: 1 },
			{ date: 2 },
			{ date: 3 },
			{ date: 4 },
			{ date: 5, rest: 'rest' },
			{ date: 6, rest: 'rest' },
			{ date: 7 },
			{ date: 8 },
			{ date: 9 },
			{ date: 10 },
			{ date: 11 },
			{ date: 12, rest: 'rest' },
			{ date: 13, rest: 'rest' },
			{ date: 14 },
			{ date: 15 },
			{ date: 16 },
			{ date: 17 },
			{ date: 18 },
			{ date: 19, rest: 'rest' },
			{ date: 20, rest: 'rest' },
			{ date: 21 },
			{ date: 22 },
			{ date: 23 },
			{ date: 24 },
			{ date: 25 },
			{ date: 26, rest: 'rest' },
			{ date: 27, rest: 'rest' },
			{ date: 28 },
			{ date: 29 },
			{ date: 30 },
			{ date: 1, disable: 'disable' },
			{ date: 2, disable: 'disable' },
			{ date: 3, disable: 'disable', rest: 'rest' },
		],
	},
	{
		month: [
			{ date: 27, disable: 'disable', rest: 'rest' },
			{ date: 28, disable: 'disable' },
			{ date: 29, disable: 'disable' },
			{ date: 30, disable: 'disable' },
			{ date: 1 },
			{ date: 2 },
			{ date: 3, rest: 'rest' },
			{ date: 4, rest: 'rest' },
			{ date: 5 },
			{ date: 6 },
			{ date: 7 },
			{ date: 8 },
			{ date: 9 },
			{ date: 10, rest: 'rest' },
			{ date: 11, rest: 'rest' },
			{ date: 12 },
			{ date: 13 },
			{ date: 14 },
			{ date: 15 },
			{ date: 16 },
			{ date: 17, rest: 'rest' },
			{ date: 18, rest: 'rest' },
			{ date: 19 },
			{ date: 20 },
			{ date: 21 },
			{ date: 22 },
			{ date: 23 },
			{ date: 24, rest: 'rest' },
			{ date: 25, rest: 'rest' },
			{ date: 26 },
			{ date: 27 },
			{ date: 28 },
			{ date: 29 },
			{ date: 30 },
			{ date: 31, rest: 'rest' },
		],
	},
]
export default data
