const dataMenu = {
	menu: [
		{ url: 'gio-lam-viec', value: 'Giờ làm việc' },
		{ url: 'xin-phep', value: 'Xin phép' },
		{ url: 'ngay-phep', value: 'Ngày phép' },
		{ url: 'quy-jvb', value: 'Quỹ JVB' },
		{ url: 'bao-cao-cong-viec', value: 'Báo cáo công việc' },
	],
	notice: [
		{
			id: 0,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Thông Báo',
			content: 'Bạn chưa gửi báo cáo tuần 39.',
			time: '4 giờ trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 1,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 39.',
			time: '11 giờ trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 2,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 39.',
			time: '',
			icon: 'StickyNote2Icon',
		},
		{
			id: 3,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 39.',
			time: 'Hôm qua',
			icon: 'StickyNote2Icon',
		},
		{
			id: 4,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 39.',
			time: '2 Ngày trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 4,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 39.',
			time: '3 ngày trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 5,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Thông Báo',
			content: 'Lịch trực nhật tháng 10/2022.',
			time: '4 ngày trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 6,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 39.',
			time: '4 ngày trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 7,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 38.',
			time: 'thứ 6 tuần trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 8,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 38.',
			time: 'thứ 5 tuần trước',
			icon: 'StickyNote2Icon',
		},
		{
			id: 8,
			url: 'https://jvb-corp.com/img/logo.png',
			heading: 'Báo cáo công việc',
			content: 'Bạn chưa gửi báo cáo tuần 38.',
			time: 'thứ 4 tuần trước',
			icon: 'StickyNote2Icon',
		},
	],
}

export default dataMenu
